services:
  # Product Server    
  product-server:
    build:
      context: . # Use root path (include docker-compose file)
      dockerfile: ProductService/Dockerfile
      # context: ./ProductService # Use path root/ProductService
      target: final
    # use networks to access internal
    ports: 
      - 5013:8080 # Map HTTP port
      - 7088:8081 # Map HTTPS port
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080 # https and http ports are exposed in Docker
      - ASPNETCORE_Kestrel__Certificates__Default__Path=https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass
      - ConnectionString_ProductDB=Server=product-db;Port=3306;Database=product_db;Uid=root;Pwd=mypass;
    networks:
      - backend
    depends_on: 
      product-db:
        condition: service_healthy
      product-migrator:
        condition: service_started
    volumes:
      - test_apigateway_product_data_volume:/app/product
  
  # Database of Product Server
  product-db:
    image: mysql:9.2.0
    environment:
      - MYSQL_DATABASE=product_db
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - 3307:3306
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - test_apigateway_product_data_volume:/var/lib/mysql  # Persist MySQL data

  # Product Migrator
  product-migrator:
    build:
      context: . # Use root path (include docker-compose file)
      dockerfile: ProductMigrator/Dockerfile
      # context: ./ProductMigrator # Use path root/ProductMigrator
      # target: final
    environment:
      - ConnectionString_ProductDB=Server=product-db;Port=3306;Database=product_db;Uid=root;Pwd=mypass;
    depends_on:
      product-db:
        condition: service_healthy
    restart: "no"
    networks:
      - backend
    stop_grace_period: 60s
    
  # User Server
  user-server:
    build:
      context: .
      dockerfile: UserService/Dockerfile
      target: final
    ports: 
      - 5050:8090
      - 7157:8091
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8091;http://+:8090
      - ASPNETCORE_Kestrel__Certificates__Default__Path=https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass
      - ConnectionString_UserDB=Server=user-db;Port=3306;Database=user_db;Uid=root;Pwd=mypass;
    networks:
      - backend
    depends_on: 
      user-db:
        condition: service_healthy
      user-migrator:
        condition: service_started
    volumes:
      - test_apigateway_user_data_volume:/app/user

  # Database of User Server
  user-db:
    image: mysql:9.2.0
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - 3308:3306
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - test_apigateway_user_data_volume:/var/lib/mysql

  # User Migrator
  user-migrator:
    build:
      context: .
      dockerfile: UserMigrator/Dockerfile
    environment:
      - ConnectionString_UserDB=Server=user-db;Port=3306;Database=user_db;Uid=root;Pwd=mypass;
    depends_on:
      user-db:
        condition: service_healthy
    restart: "no"
    networks:
      - backend
    stop_grace_period: 60s

networks:
  backend:
    driver: bridge
volumes:
  test_apigateway_product_data_volume:
    external: true
  test_apigateway_user_data_volume:
    external: true